apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-test
  name: nginx-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-test
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 4
  labels:
    app: nginx-test
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nginx-test
    helm.sh/chart: nginx-0.1.0
    version: 0.1.0
  name: nginx-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-test
      app.kubernetes.io/name: nginx-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kmse.jekins.build: "1"
      creationTimestamp: null
      labels:
        app: nginx-test
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: nginx-test
        version: 0.1.0
    spec:
      volumes:
      - name: index
        persistentVolumeClaim:
          claimName: nginx-pvc
      containers:
      - image: hub.kce.ksyun.com/ksyun-public/nginx:latest
        imagePullPolicy: Always
        name: kce-nginx
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root
          name: index
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ksyunregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
